pipeline:
  identifier: Build_manish_patel_harnesscd_example_apps_1720178671454
  name: Build harnesscd-example-apps
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1719602273076
        repoName: manish-patel/harnesscd-example-apps
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Arm64
            os: MacOS
          runtime:
            spec: {}
            type: Docker
        type: CI
